title: Bioinformatics Spring School 2023
email: murray.cadzow@otago.ac.nz
baseurl: "/2023/"
url: "https://otagobioinformaticsspringschool.github.io"
theme: jekyll-theme-leap-day

day1_url: "day1.html"
